.PHONY: clean All

All:
	@echo "----------Building project:[ lab0 - Debug ]----------"
	@$(MAKE) -f  "lab0.mk"
clean:
	@echo "----------Cleaning project:[ lab0 - Debug ]----------"
	@$(MAKE) -f  "lab0.mk" clean
