.PHONY: clean All

All:
	@echo "----------Building project:[ lab01 - Debug ]----------"
	@cd "lab01" && $(MAKE) -f  "lab01.mk"
clean:
	@echo "----------Cleaning project:[ lab01 - Debug ]----------"
	@cd "lab01" && $(MAKE) -f  "lab01.mk" clean
